### ISSUE TITLE
Publishing on opera addons site

### ISSUE THREAD

**Issue by shwetank** [NiklasGollenstede/wikipedia-peek#1]
Would be nice to have it on the official opera addons site. Let me know if you need any help with that.

**Comment by NiklasGollenstede** [comment]
That's curious. I've never worked with Opera so far, but as it happens I have created an account there and uploaded the extension less than 12 hours ago :D
It's currently awaiting their review, I think everything should go smooth there.
Thaks a lot for your interest!

**Comment by shwetank** [comment]
Seems like the extension was provisionally disproved by the moderator. This is because 
1. HTML tags in description are not allowed.
2. 2nd screenshot doesn't come from Opera.

For point 1, could you re-submit the extension but without html tags in the description. 

As for screenshots, if you want, I could take some in Opera and send you those....

**Comment by shwetank** [comment]
![operascreenshot](https://cloud.githubusercontent.com/assets/43538/16517795/e39ee63c-3f9c-11e6-9f7d-5e9d6c3a7a36.png)

Attached screenshot for Opera. You can use this when submitting it this time. :)

**Comment by NiklasGollenstede** [comment]
Thanks, I shrunk that screenshot a bit so it looks better in the (not to big) review.
If that's fine with you, I'll commit the shrunken version into this repository.

**Comment by shwetank** [comment]
Great 👍

**Comment by NiklasGollenstede** [comment]
Ok, I think we are done here
