### ISSUE TITLE
Redirected articles with Section linking

### ISSUE THREAD

**Issue by BrontoRed** [NiklasGollenstede/wikipedia-peek#10]
Sometimes (very rarely) Wikipedia links point on articles, that redirect request to section of another article. Although wikipedia-peek support Section linking, in this case it doesn't work.
Here is a link on [redirected article](https://ru.wikipedia.org/wiki/%D0%A2%D0%B5%D1%87%D0%BA%D0%B0) and [direct Section linking](https://ru.wikipedia.org/wiki/%D0%90%D0%BD%D0%B0%D1%82%D0%BE%D0%BC%D0%B8%D1%8F_%D0%B8_%D1%84%D0%B8%D0%B7%D0%B8%D0%BE%D0%BB%D0%BE%D0%B3%D0%B8%D1%8F_%D0%BC%D0%BB%D0%B5%D0%BA%D0%BE%D0%BF%D0%B8%D1%82%D0%B0%D1%8E%D1%89%D0%B8%D1%85#.D0.AD.D1.81.D1.82.D1.80.D0.B0.D0.BB.D1.8C.D0.BD.D1.8B.D0.B9_.D1.86.D0.B8.D0.BA.D0.BB) from that article.

**Comment by NiklasGollenstede** [comment]
I'm pretty sure that is related to URL-encoding (and will thus only happen for segment ids that contain non-Latin characters).

I think I have fixed it. Now both links have the same preview, that of the second link. Is that the desired behavior?

**Comment by BrontoRed** [comment]
Please, update wikipedia-peek in Firefox addons. [Latest available version](https://addons.mozilla.org/firefox/addon/wikipedia-peek/versions/beta) is 2.8.5b17 from April 29, 2017.

**Comment by BrontoRed** [comment]
Thanks! Works as expected.
