### ISSUE TITLE
off-wikipedia?

### ISSUE THREAD

**Issue by edsu** [NiklasGollenstede/wikipedia-peek#11]
Thanks for this plugin!

I was wondering if you ever considered having it run off of Wikipedia, for when you discover links to Wikipedia elsewhere on the Web. Is there a downside I'm not seeing to doing this?

**Comment by BrontoRed** [comment]
You can use latest beta version from [here](https://addons.mozilla.org/firefox/addon/wikipedia-peek/versions/beta). It has much more options.

**Comment by edsu** [comment]
Thanks!
