### ISSUE TITLE
Section linking (anchors)

### ISSUE THREAD

**Issue by BrontoRed** [NiklasGollenstede/wikipedia-peek#4]
Currently wikipedia-peek doesn't support Section linking (anchors), which is used in any context of articles and sometimes can be used to provide direct links to article sections. Compare [link on article](https://en.wikipedia.org/wiki/Shill) and [link on section of this article](https://en.wikipedia.org/wiki/Shill#Internet).
Would be great to add this as an option.

**Comment by NiklasGollenstede** [comment]
Thanks, fixed in 2.8.5b12
