### ISSUE TITLE
"values" is read only

### ISSUE THREAD

**Issue by BrontoRed** [NiklasGollenstede/wikipedia-peek#5]
Hi!
Don't know what happened, but I can't change "values" in settings of wikipedia-peek.
On Firefox 52.0.1 + Wikipedia Peek 2.8.5b12 constantly get this message: ["values" is read only](http://imgur.com/a/F2tO3)

**Comment by NiklasGollenstede** [comment]
Yupp, made some backend changes without testing them properly. Fixed it in a single line.

v2.8.5b13 should work again. Thanks!
