### ISSUE TITLE
Private Browsing and wikipedia-peek

### ISSUE THREAD

**Issue by BrontoRed** [NiklasGollenstede/wikipedia-peek#6]
Thanks for quickly fixing all the small issues of wikipedia-peek. But the more I use it, the more I find out.
One more from me: Wikipedia Peek doesn't work in Private windows of Firefox, which, of course, is a pity.

**Comment by NiklasGollenstede** [comment]
Did you check that?
![image](https://cloud.githubusercontent.com/assets/10552031/24194219/88d1d0e2-0ef5-11e7-8291-088ec8dcd5fd.png)

This add-on has quite some privacy implications, so it really can't be turned on by default. And even if it is turned on, it currently doesn't treat private tabs any different than others.

**Comment by BrontoRed** [comment]
Yes, that was the reason. I didn't even thought that this function needs an extra option in settings. Thank you!
