### ISSUE TITLE
"X" sign on links

### ISSUE THREAD

**Issue by BrontoRed** [NiklasGollenstede/wikipedia-peek#8]
Sorry, if I get too bothersome, but consider one more issue: on hovering links that are not connected with wikipedia I always get gray "X" sign. Wikipedia-peek 2.8.5b15, Readability.js is disabled.
![x on links](https://cloud.githubusercontent.com/assets/23166071/25134989/b16863d0-2459-11e7-9aca-cd7539b74077.gif)

**Comment by NiklasGollenstede** [comment]
Jupp. I just added that. In the touch-mode, a first tap on a link tries to open the preview, only the second tap is passed through to the link itself.
Previously it was difficult to see that logic when the preview could not be loaded. Now it's very simple: tab a normal link and the preview will be loaded, tab a link that has a preview, the load animation or that cross, an it will click the link.

Admittedly that cross is somewhat ugly and not really needed in non-touch mode. I think I will disable it there as soon as I find the time.
